-- The source of truth is supabase/migrations/.
-- New project: apply all migration files in timestamp order. The historical
-- RLS migration versions have been made safe for a fresh deployment.
-- Existing project with the old recall tables: apply only
-- 20260926000000_account_auth.sql. It removes any old broad policies.
-- This file is an index, not a standalone schema to paste into SQL Editor.
